version: "3"
services:
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - REACT_APP_BACKEND_URL=$SITE_URL
      - REACT_APP_BACKEND_PORT=$BACKEND_PORT
    ports:
      - $FRONTEND_PORT:80
    links:
      - backend
    networks:
      - sushiOM
  
  backend:
    build: ./backend
    container_name: backend
    environment:
      - PORT=$BACKEND_PORT
      - FRONTEND_URL=$SITE_URL
      - FRONTEND_PORT=$FRONTEND_PORT
      - JWT_SECRET=$JWT_SECRET
      - JWT_EXPIRATION=$JWT_EXPIRATION
      - DELETE_GROUPS_INTERVAL=$DELETE_GROUPS_INTERVAL
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGDATABASE=$PGDATABASE
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    depends_on:
      - "postgres"
    networks:
      - sushiOM
    
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
    - /data/postgres:/data/postgres
    environment:
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_DB=$PGDATABASE
    networks:
    - sushiOM
 
networks:
  sushiOM:
    driver: bridge